#!/bin/bash

cat << EOF


 ███▄    █ ▓█████  ▄████▄   ██▀███   ▒█████   ███▄ ▄███▓ ▄▄▄       ███▄    █  ▄████▄  ▓█████  ██▀███  
 ██ ▀█   █ ▓█   ▀ ▒██▀ ▀█  ▓██ ▒ ██▒▒██▒  ██▒▓██▒▀█▀ ██▒▒████▄     ██ ▀█   █ ▒██▀ ▀█  ▓█   ▀ ▓██ ▒ ██▒
▓██  ▀█ ██▒▒███   ▒▓█    ▄ ▓██ ░▄█ ▒▒██░  ██▒▓██    ▓██░▒██  ▀█▄  ▓██  ▀█ ██▒▒▓█    ▄ ▒███   ▓██ ░▄█ ▒
▓██▒  ▐▌██▒▒▓█  ▄ ▒▓▓▄ ▄██▒▒██▀▀█▄  ▒██   ██░▒██    ▒██ ░██▄▄▄▄██ ▓██▒  ▐▌██▒▒▓▓▄ ▄██▒▒▓█  ▄ ▒██▀▀█▄  
▒██░   ▓██░░▒████▒▒ ▓███▀ ░░██▓ ▒██▒░ ████▓▒░▒██▒   ░██▒ ▓█   ▓██▒▒██░   ▓██░▒ ▓███▀ ░░▒████▒░██▓ ▒██▒
░ ▒░   ▒ ▒ ░░ ▒░ ░░ ░▒ ▒  ░░ ▒▓ ░▒▓░░ ▒░▒░▒░ ░ ▒░   ░  ░ ▒▒   ▓▒█░░ ▒░   ▒ ▒ ░ ░▒ ▒  ░░░ ▒░ ░░ ▒▓ ░▒▓░
░ ░░   ░ ▒░ ░ ░  ░  ░  ▒     ░▒ ░ ▒░  ░ ▒ ▒░ ░  ░      ░  ▒   ▒▒ ░░ ░░   ░ ▒░  ░  ▒    ░ ░  ░  ░▒ ░ ▒░
   ░   ░ ░    ░   ░          ░░   ░ ░ ░ ░ ▒  ░      ░     ░   ▒      ░   ░ ░ ░           ░     ░░   ░ 
         ░    ░  ░░ ░         ░         ░ ░         ░         ░  ░         ░ ░ ░         ░  ░   ░     
                  ░                                                          ░                        
Version: 0.0.1

By @23vs3c
I'm not responsible for what you do with this software. ;)
EOF

SHOW_HELP=0
FULL_RECON=1
DNS_RECON=0
TECH_RECON=0
CMS_TYPE="Unknown"
PORT_RECON=0
VULN_RECON=0
SKIP_DNS=0
SKIP_TECH=0
SKIP_PORT=0
SKIP_VULN=0
SAVE_FILE=0
TIMESTAMP="$(date +%s)"
FILENAME="/tmp/necromancer-${TIMESTAMP}.txt"
TARGET=""
SCAN_TYPE="FULL"

basic_usage () {
	echo << EOF
Usage: ./necromancer [options] <target>
[Options]
Note: Full scan mode is enabled by default.

General:
  -h			Display this help screen.
  --help		Display extended help.
Scan:
  -f, --full		Extensive extended scan of target.
  -d, --dns		DNS scan of target.
  -t, --tech		Technologies scan of target.
  -ps, --port-scan	Port scan
  -vs, --vuln-scan	Vulnerability scan
EOF
	exit
}

extended_usage () {
	echo << EOF
Usage: ./necromancer [options] <target>
[Options]
Note: Full scan mode is enabled by default.

General:
  -h			Display this help screen.
  --help		Display extended help.
Scan:
  -f, --full		Extensive extended scan of target.
  -d, --dns		DNS scan of target.
  -t, --tech		Technologies scan of target.
  -ps, --port-scan	Port scan
  -vs, --vuln-scan	Vulnerability scan
  -sd, --skip-dns	Skip the DNS scan. Used in conjunction with -f/--full.
  -st, --skip-tech	Skip technology scan. Used in conjunction with -f/--full.
  -sp, --skip-ports	Skip port scan. Used in conjunction with -f/--full.
  -sv, --skip-vuln	Skip vulnerability scan. Used in conjunction with -f/--full.
Output:
  -o, --output <file>	Output all data to the specified file.
EOF
	exit
}

for arg in "$@"
do
	case $arg in
		-h)
			basic_usage
		;;
		--help)
			extended_usage
		;;
		-w|--waf)
			shift
			WAF_SCAN=1
			FULL_RECON=0
		;;
		-f|--full)
			shift
			FULL_RECON=1
		;;
		-d|--dns)
			shift
			DNS_RECON=1
			FULL_RECON=0
		;;
		-t|--tech)
			shift
			TECH_RECON=1
			FULL_RECON=0
		;;
		-ps|--port-scan)
			shift
			PORT_RECON=1
			FULL_RECON=0
		;;
		-vs|--vuln-scan)
			shift
			VULN_RECON=1
			FULL_RECON=0
		;;
		-sd|--skip-dns)
			shift
			SKIP_DNS=1
		;;
		-st|--skip-tech)
			shift
			SKIP_TECH=1
		;;
		-sp|--skip-ports)
			shift
			SKIP_PORT=1
		;;
		-sv|--skip-vuln)
			shift
			SKIP_VULN=1
		;;
		-o|--output)
			shift
			SAVE_FILE=1
			FILENAME="$2"
			shift
		;;
		*)
			TARGET="$1"
	esac
done

if [[ $TARGET == "" ]]; then
	echo "You must specify a target."
	basic_usage
fi

if [[ $WAF_RECON == 1 ]]; then
	SCAN_TYPE="WAF"
fi
if [[ $DNS_RECON == 1 ]]; then
	SCAN_TYPE="DNS"
fi
if [[ $TECH_RECON == 1 ]]; then
	SCAN_TYPE="TECH"
fi
if [[ $PORT_RECON == 1 ]]; then
	SCAN_TYPE="PORT"
fi
if [[ ${VULN_RECON} == 1 ]]; then
	SCAN_TYPE="VULN"
fi

if [[ ${SAVE_FILE} == 1 ]]; then
	touch $FILENAME
fi

echo
echo "-------------------------------------------------"
echo "# TARGET: ${TARGET}"
echo "# SCAN TYPE: ${SCAN_TYPE}"
echo "-------------------------------------------------"
echo

if [[ $FULL_RECON == 1 || $WAF_RECON == 1 ]]; then
	if [[ ! $SKIP_WAF == 1 ]]; then
		echo
		echo "=========== WAF SCAN ==========="
		echo
		if [[ $SAVE_FILE == 1 ]]; then
			wafw00f ${TARGET} | tee -a ${FILENAME}
		else
			wafw00f ${TARGET}
		fi
	fi
fi

if [[ $FULL_RECON == 1 || $DNS_RECON == 1 ]]; then
	if [[ ! $SKIP_DNS == 1 ]]; then
		echo
		echo "=========== DNS SCAN ==========="
		echo
		if [[ $SAVE_FILE == 1 ]]; then
			dnsrecon -d ${TARGET} -asgbkz | tee -a ${FILENAME}
		else
			dnsrecon -d ${TARGET} -asgbkz
		fi
	fi
fi

if [[ $FULL_RECON == 1 || $TECH_RECON == 1 ]]; then
	if [[ ! $SKIP_TECH == 1 ]]; then
		echo
		echo "=========== TECH SCAN ==========="
		echo
		if [[ $SAVE_FILE == 1 ]]; then
			whatweb ${TARGET} | tee -a ${FILENAME}
		else
			whatweb ${TARGET}
		fi
	fi
fi

if [[ $FULL_RECON == 1 || $VULN_RECON == 1 || $PORT_RECON == 1 ]]; then
	if [[ $FULL_RECON == 1 || $VULN_RECON == 1 ]]; then
		echo
		echo "=========== VULN SCAN ==========="
		echo
		if [[ $SAVE_FILE == 1 ]]; then
			nmap -vvv -A ${TARGET} | tee -a ${FILENAME}
		else
			nmap -vvv -A ${TARGET}
		fi
	fi
	if [[ $PORT_RECON == 1 ]]; then
		echo
		echo "=========== PORT SCAN ==========="
		echo
		if [[ $SAVE_FILE == 1 ]]; then
			nmap -vvv -sV ${TARGET} | tee -a ${FILENAME}
		else
			nmap -vvv -sV ${TARGET}
		fi
	fi
fi

exit
